image: gitpod/workspace-node

ports:
  - port: 3001        # WebSocket server
    onOpen: ignore
    visibility: public
  - port: 5173        # Vite dev server
    onOpen: open-preview
    visibility: public

tasks:
  - name: Install deps
    init: |
      cd server && npm install
      cd ../docs && npm install
    command: echo "Dependencies installed. Use the other terminals to run backend and frontend."

  - name: Backend
    command: |
      cd server
      npm run dev

  - name: Frontend
    command: |
      cd docs
      export VITE_WS_URL=$(echo $GITPOD_WORKSPACE_URL | sed 's#https://#wss://3001-#')
      npm run dev -- --host 0.0.0.0 --port 5173
